version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: itee-spot-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=itee-spot
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
    ports:
      - 1234:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped

volumes:
  pgdata:
  redis-data: