export const INVALID_ACCESS_TOKEN = 'INVALID_ACCESS_TOKEN';
export const EXPIRED_ACCESS_TOKEN = 'EXPIRED_ACCESS_TOKEN';

export const EXPIRED_REFRESH_TOKEN = 'EXPIRED_REFRESH_TOKEN';
export const INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN';
export const EXISTED_REFRESH_TOKEN = 'EXISTED_REFRESH_TOKEN';
export const NOT_EXISTED_REFRESH_TOKEN = 'NOT_EXISTED_REFRESH_TOKEN';

export const EXISTED_SESSION_ERROR = 'EXISTED_SESSION_ERROR';
export const NOT_EXISTED_SESSION_ERROR = 'NOT_EXISTED_SESSION_ERROR';

export const EXISTED_USER_ERROR = 'EXISTED_USER_ERROR';
export const NOT_EXISTED_USER_ERROR = 'NOT_EXISTED_USER_ERROR';
export const INVALID_CREDENTIALS_ERROR = 'INVALID_CREDENTIALS_ERROR';
export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
