// Access Token Error
export const INVALID_ACCESS_TOKEN = 'INVALID_ACCESS_TOKEN';
export const EXPIRED_ACCESS_TOKEN = 'EXPIRED_ACCESS_TOKEN';
// Refresh Token Error
export const EXPIRED_REFRESH_TOKEN = 'EXPIRED_REFRESH_TOKEN';
export const INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN';
export const EXISTED_REFRESH_TOKEN = 'EXISTED_REFRESH_TOKEN';
export const NOT_EXISTED_REFRESH_TOKEN = 'NOT_EXISTED_REFRESH_TOKEN';
export const REVOKED_REFRESH_TOKEN = 'REVOKED_REFRESH_TOKEN';
// Session Error
export const EXISTED_SESSION_ERROR = 'EXISTED_SESSION_ERROR';
export const NOT_EXISTED_SESSION_ERROR = 'NOT_EXISTED_SESSION_ERROR';
// User/Profile Error
export const EXISTED_USER_ERROR = 'EXISTED_USER_ERROR';
export const NOT_EXISTED_USER_ERROR = 'NOT_EXISTED_USER_ERROR';
export const INVALID_CREDENTIALS_ERROR = 'INVALID_CREDENTIALS_ERROR';

export const GITHUB_EMAIL_NOT_FOUND = 'GITHUB_EMAIL_NOT_FOUND';
// Event Error
export const NOT_EXISTED_EVENT_ERROR = 'NOT_EXISTED_EVENT_ERROR';

// Event Challenge Error
export const NOT_EXISTED_CHALLENGE_ERROR = 'NOT_EXISTED_CHALLENGE_ERROR';

// Event Award Error
export const NOT_EXISTED_AWARD_ERROR = 'NOT_EXISTED_AWARD_ERROR';

// Criteria Error
export const NOT_EXISTED_CRITERIA_ERROR = 'NOT_EXISTED_CRITERIA_ERROR';

// Group Error
export const NOT_EXISTED_GROUP_ERROR = 'NOT_EXISTED_GROUP_ERROR';
export const DUPLICATE_GROUP_ERROR = 'DUPLICATE_GROUP_ERROR';
export const EXISTED_GROUP_ERROR = 'EXISTED_GROUP_ERROR';

// Other Error
export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
export const INVALID_INCLUDE_ERROR = 'INVALID_INCLUDE_ERROR';
export const UNAUTHORIZED = 'UNAUTHORIZED'


// Slot Error
export const NOT_EXISTED_SLOT_ERROR = 'NOT_EXISTED_SLOT_ERROR';
export const SLOT_ALREADY_PARTICIPATED_ERROR = 'SLOT_ALREADY_PARTICIPATED_ERROR';
export const SLOT_NOT_PARTICIPATED_ERROR = 'SLOT_NOT_PARTICIPATED_ERROR';
export const SLOT_NOT_STARTED = 'SLOT_NOT_STARTED';
export const SLOT_ALREADY_ENDED = 'SLOT_ALREADY_ENDED';
export const SLOT_OVERLAP_ERROR = 'SLOT_OVERLAP_ERROR';


// Collection Error
export const NOT_EXISTED_COLLECTION_ERROR = 'NOT_EXISTED_COLLECTION_ERROR';
